# Generated by Django 2.1.4 on 2019-01-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitCameraItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tg_chat_id', models.BigIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.CharField(max_length=2048)),
                ('what_to_detect', models.CharField(choices=[('person', 'человек'), ('bicycle', 'велосипед'), ('car', 'автомобиль'), ('airplane', 'самолет'), ('bus', 'автобус'), ('train', 'поезд'), ('truck', 'грузовик'), ('boat', 'лодка'), ('bird', 'птица'), ('cat', 'кошка'), ('dog', 'собака'), ('horse', 'лошадь'), ('umbrella', 'зонтик'), ('bottle', 'бутылка'), ('wine glass', 'бокал вина'), ('cup', 'чашка'), ('pizza', 'пицца')], max_length=100)),
                ('detection_threshold', models.IntegerField()),
                ('detection_enabled', models.BooleanField(default=True)),
                ('notification_type', models.CharField(choices=[('appearance', 'появление и пропажа'), ('presence', 'наличие'), ('absence', 'отсутствие')], max_length=100)),
                ('last_time_object_presented', models.BooleanField(default=False)),
                ('edge_left', models.IntegerField(default=0)),
                ('edge_top', models.IntegerField(default=0)),
                ('edge_right', models.IntegerField(default=100)),
                ('edge_bottom', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
