# tuples (key, display_name)
DETECTION_ITEMS = [
  ('person', 'человек'),
  ('bicycle', 'велосипед'),
  ('car', 'автомобиль'),
  ('airplane', 'самолет'),
  ('bus', 'автобус'),
  ('train', 'поезд'),
  ('truck', 'грузовик'),
  ('boat', 'лодка'),
  ('bird', 'птица'),
  ('cat', 'кошка'),
  ('dog', 'собака'),
  ('horse', 'лошадь'),
  ('umbrella', 'зонтик'),
  ('bottle', 'бутылка'),
  ('wine glass', 'бокал вина'),
  ('cup', 'чашка'),
  ('pizza', 'пицца'),
]
